apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-env-config
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'https://dg0301.20.214.196.128.nip.io/api/auth',
      MYSUB_URL: 'https://dg0301.20.214.196.128.nip.io/api/mysub',
      RECOMMEND_URL: 'https://dg0301.20.214.196.128.nip.io/api/recommend'
    }
